version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: "dev"
    volumes:
      - ./src:/usr/app/src
    command: "npm run dev"
    ports:
      - '3000:3000'
